### PR TITLE
Use signalstats instead of linear_fit for waveform slopes

### PR DESCRIPTION
**Pull request by oschulz**
Removes memory copies, also `RadiationDetectorDSP.signalstats` is very fast.

Also removes dependencies CurveFit and LsqFit (both rather heavy).

### CODE REVIEW

**Comment by oschulz** [comment]
Test on Julia v1.6 should pass after JuliaRegistries/General#85327 .

**Comment by oschulz** [comment]
@sagitta42 should be good to go?

**Comment by sagitta42** [comment]
You can merge, but the sort of actual "main" version is currently in my fork's master - it does not use LegendDataManagement, but it does everything that it should do, which the main branch here doesn't.

Some people are already testing that master, and I'm polishing it up. What would be more convenient for you in terms of dev flow? Should I first PR that into main, and then we do this update? Or first you merge this, then I pull rebase?

The main point of divergence would be I'm using CurveFit for impurity profile, so no need to remove it. Sorry again, as I said, the current main on legend-exp is actually very out of date because I've never pushed a lot of stuff since last August because there was no interest in the framework.

Another difference is that I reverted back to using an "internal" LegendGeSim function for `LEGEND_SolidStateDetector`, because the way it's implemented now in main here using LegendDataManagement is not correct. It sets a constant temperature, does not set operating voltage, no impurity profile, no dead layer etc. So it's useless. Again, sorry, the whole "environment settings" with temperature and opV was also only on my fork, I didn't PR because of two PRs of Lukas that were clashing with mine way back during Software Tutorial and then last September, so I was just working with my code on my fork ignoring main because I just got frustrated with people making changes without consulting me and without waiting for me to PR

**Comment by oschulz** [comment]
> The main point of divergence would be I'm using CurveFit for impurity profile, so no need to remove it. 

Ok, I've changed the PR to keep CurveFit.
depdencency.
> Should I first PR that into main, and then we do this update? Or first you merge this, then I pull rebase?

I'd suggest to merge this PR first, since it should be orthogonal to your changes (I think) and it get's rid of a somewhat heavy dependency (LsqFit).

Longer term we could use Optim directlly for the impurity profile fits and then get rid of CurveFit as well.

> "internal" LegendGeSim function for LEGEND_SolidStateDetector, because the way it's implemented now in main here using LegendDataManagement is not correct. It sets a constant temperature, does not set operating voltage, no impurity profile, no dead layer etc. 

I suggest to (after this PR) merge your master/main branch back in here as soon as possible (we need to remove type piracy though). Then we can update the implementation in LegendDataManagement accordingly, and it that works out nicely, then we can remove the code from LegendGeSim again and rely on LegendDataManagement.

**Comment by sagitta42** [comment]
Ok then merge this.

Yeah my next plan is to re-introduce LegendDataManagement but properly. That would mean I will first construct geometry and create a `SolidStateDetector` object, and then afterwards set some parameters if possible, or if not, I'll take chunks of the original object and construct a new one based on those + temperature/opV/impurity based on sim settings

**Comment by oschulz** [comment]
> I will first construct geometry and create a SolidStateDetector object, and then afterwards set some parameters if possible

Sounds good - I think that should be possible. And we could of course add some keyword arguments to the constructor to set very common things that users often need directly at detector construction time.

**Pull request merged**
