### PR TITLE
Avoid caching simulation results in documentation

### PR DESCRIPTION
**Pull request by fhagemann**
Attempt to avoid caching simulation results in documentation

### CODE REVIEW

**Comment by fhagemann** [comment]
The documentation for this PR should be found here:
https://legend-exp.github.io/LegendGeSim.jl/previews/PR55

**Comment by fhagemann** [comment]
I think this fixed the issue:
@sagitta42: if [this](https://legend-exp.github.io/LegendGeSim.jl/previews/PR55) looks good to you, I would propose to merge this.

**Comment by sagitta42** [comment]
@fhagemann I commented also in the closed PR in more detail, I think this version is the solution.

**Comment by fhagemann** [comment]
Then  I will merge this one to have the documentation online.

**Pull request merged**
